<a href="https://colab.research.google.com/github/LLewis/ai-deep-learning/blob/main/Copy_of_DUDL_math_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#import libraries
import numpy as np
import torch

#Using numphy  --------------------------

#create a row vector  using array function
# the first row of the 
nv = np.array([[1,2,3,4,5,6,7,8,9]])
print(nv), print(' ')

#transpose it to column vector using the
# T transpose function on the np.array object
print(nv.T), print(' ')


#transpose the transpose back to 
#it's original state
nvT = nv.T
print(nvT.T)
print()

#------------------------------------------

#create a matrix  two rows and four column matrix
nM = np.array([[1,2,3,4],[5,6,7,8]])
print(nM), print(' ')

#transpose the matrix into two vector columns (lists)
print(nM.T), print(' ')

#transpose the transpose
nMT = nM.T
print(nMT.T)

#Using pytorch  --------------------------

#create a tensor row vector
tv = torch.tensor([[1,2,3,4]])
print(tv), print(' ')

#transpose it to a tensor column vector
print(tv.T), print(' ')

#transpose the transpose
tvT = tv.T
print(tvT.T)
print(' ')

#------------------------------------------

#create a matrix  two rows and four column matrix
tM = torch.tensor([[1,2,3,4,],[5,6,7,8]])
print(tM), print(' ')

#transpose it
print(tM.T), print(' ')

#transpose the transpose
tMT = tM.T
print(tMT.T), print(' ')



#example of different numphy and pytorch data types of variables above

print(f'Variable nv is of type {type(nv)}')
print(f'Variable nM is of type {type(nM)}')
print(f'Variable tv is of type {type(tv)}')
print(f'Variable tM is of type {type(tM)}')

[[1 2 3 4 5 6 7 8 9]]
 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
 
[[1 2 3 4 5 6 7 8 9]]

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
Variable nv is of type <class 'numpy.ndarray'>
Variable nM is of type <class 'numpy.ndarray'>
Variable tv is of type <class 'torch.Tensor'>
Variable tM is of type <class 'torch.Tensor'>
