<a href="https://colab.research.google.com/github/LLewis/ai-deep-learning/blob/main/DUDL_math_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. In fact tensors are merely a generalisation of scalars and vectors; a scalar is a zero rank tensor, and a vector is a first rank tensor.

In [23]:

#create random matrices
import numpy as np
import torch 


print('******** Using numphy creating matrices - arrays')
#Using numphy
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

#try manipulating matrices
print(np.round(A@B, 2)), print(' ')
#print(np.round(A@C, 2)), print(' ')
#print(np.round(A.T@C, 2)), print(' ')
#print(np.round(B@C, 2)), print(' ')
#print(np.round(C.T@A, 2)), print(' ')

print('******** Using Pytorch creating tensors')
#Using Pytorch
#create random matrices 
A = torch.randn(3, 4)   #pytorch tensor
B = torch.randn(4,5)
C1 = np.random.randn(4, 7)  #a numphy matrix
C2 = torch.tensor(C1, dtype=torch.float)

#try multiplying matrices
##print(np.round(A@B, 2)), print(' ')
#print(np.round(A@B.T, 2)), print(' ')
#print(np.round(A@C1, 2)), print(' ')
print(np.round(A@C2, 2)), print(' ')

******** Using numphy creating matrices - arrays
[[ 0.08 -1.43  3.78 -1.89  3.65]
 [-0.45  1.32 -0.68  3.   -1.3 ]
 [ 0.53 -1.98 -1.34 -0.96  0.99]]
 
******** Using Pytorch creating tensors
tensor([[ 0.3600, -0.1000,  0.1500, -0.5200,  0.2100,  0.2900,  0.0500],
        [ 4.9600, -2.6400,  9.9400, -8.7600, -0.3200,  5.6500, -2.0300],
        [ 4.1600, -0.7400,  3.8800, -4.2700,  0.9700,  2.7600,  0.1500]])
 


(None, None)

In [1]:
#import libraries
import numpy as np
import torch

#create a row vector  using array function
# the first row of the 
nv = np.array([[1,2,3,4,5,6,7,8,9]])
print(nv), print(' ')

#transpose it to column vector using the
# T transpose function on the np.array object
print(nv.T), print(' ')


#transpose the transpose back to 
#it's original state
nvT = nv.T
print(nvT.T)

#------------------------------------------

#create a matrix  two rows and four column matrix
nM = np.array([[1,2,3,4],[5,6,7,8]])
print(nM), print(' ')

#transpose the matrix 
print(nM.T), print(' ')

#transpose the transpose
nMT = nM.T
print(nMT.T)





[[1 2 3 4 5 6 7 8 9]]
 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
 
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
