<a href="https://colab.research.google.com/github/LLewis/ai-deep-learning/blob/main/DUDL_math_min_max_argmin_argmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries

import numpy as np
import torch
import torch.nn as nn

#create a vector
v = np.array([1, 40,2,-3])

#find and report the maximum and minimum values usin min and max functions
minval = np.min(v)
maxval = np.max(v)
print('Min,Max: %g,%g' %(minval, maxval))

#find and report the index value of the  minimum value and maximum value
minidx = np.argmin(v)
maxidx = np.argmax(v)
print('Min,Max indices: %g,%g' %(minidx, maxidx)), print(' ')

#confirm index value
print(f'Min val is {v[minidx]}, Max val is {v[maxidx]}')
print()

#repeat with matirix
#can calculate multiple types of minimum values
#min value in a row or max valu in a column or min value for between all elements in matrix
M = np.array([[0,1,10], [20,8,5]])

print('Matrix')
print(M), print(' ')

#various minima in matrix
minvals1 = np.min(M) # minimum from entire matrix
minvals2 = np.min(M, axis=0) #minimum of each column (accross rows)
minvals3 = np.min(M, axis=1) #minimum of each row (accross columns)

print(minvals1)
print(minvals2)
print(minvals3)

#many minima in matrix using argmin or argmax functions
minidx1 = np.argmin(M) # minimum from entire matrix
minidx2 = np.argmin(M, axis=0) #minimum of each column (accross rows)
minidx3 = np.argmin(M, axis=1) #minimum of each row (accross columns


print(M), print(' ') #reminder.  min value of matrix 0
print(minidx1)  
print(minidx2)
print(minidx3)


#USING Pytorch

#create a vector on deminsional tensor
v = torch.tensor([1,50,2,-8])

#find and report the maximum and minimum  values
minval = torch.min(v)
maxval = torch.max(v)

print('Min,Max: %g,%g' %(minval, maxval))

#for the argmin and argmax functions
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min,Max indices: %g,%g' %(minidx, maxidx)), print(' ')

#confirm index value
print(f'Min val is {v[minidx]}, Max val is {v[maxidx]}')
print()

#repeat with matrix
M = torch.tensor([[0,1,10], [20,8,5]])
print(M), print(' ')

#many minima in matrix using argmin or argmax functions. 
min1 = torch.min(M) # minimum from entire matrix two deminsionalo tensor
min2 = torch.min(M, axis=0) #minimum of each column (accross rows)
min3 = torch.min(M, axis=1) #minimum of each row (accross columns)

#print out
print(min1), print(' ') #min value of matrix 0
print(min2)  , print(' ') #print matrix containing lowest value in each column
print(min2.values)
print(min2.indices)


type(min2) #min2 is a tuple containing the tensor values and indicies









Min,Max: -3,40
Min,Max indices: 3,1
 
Min val is -3, Max val is 40

Matrix
[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]
[[ 0  1 10]
 [20  8  5]]
 
0
[0 0 1]
[0 2]
Min,Max: -8,50
Min,Max indices: 3,1
 
Min val is -8, Max val is 50

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
tensor([0, 0, 1])


torch.return_types.min