<a href="https://colab.research.google.com/github/LLewis/ai-deep-learning/blob/main/DUDL_math_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#import libraries
import numpy as np
import torch

#create a row vector  using array function
# the first row of the 
nv = np.array([[1,2,3,4,5,6,7,8,9]])
print(nv), print(' ')

#transpose it to column vector using the
# T transpose function on the np.array object
print(nv.T), print(' ')


#transpose the transpose back to 
#it's original state
nvT = nv.T
print(nvT.T)

#------------------------------------------

#create a matrix  two rows and four column matrix
nM = np.array([[1,2,3,4],[5,6,7,8]])
print(nM), print(' ')

#transpose the matrix 
print(nM.T), print(' ')

#transpose the transpose
nMT = nM.T
print(nMT.T)





[[1 2 3 4 5 6 7 8 9]]
 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
 
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
