<a href="https://colab.research.google.com/github/LLewis/ai-deep-learning/blob/main/Lewis_ANN_numParameters_wide_deep_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
#import libraries
import numpy as np
import torch
import torch.nn as nn

# Build two models
#Counting weights, which are the module parameters

#a wide or breadth is determined by its number of nodes in a layer
widenetwork = nn.Sequential(

    #hidden layer, the object (nn.Linear) is the weight metrics for input 2, 4 that connect to the hiddent layer - visual ,
    #its the transformation layer ( connecting arrows) that gets mapped to hidden layer
    nn.Linear(2,4),  #hidden layer
    nn.Linear(4,3)   #output layer
)

# a deep network is determined by its number of layers,
#so this sequential deep newtork has three layers
deepnetwork = nn.Sequential(
    nn.Linear(2,2), #transformation layer (connecting arrows) mapped to --> #hidden layer
    nn.Linear(2,2), #hidden layer
    nn.Linear(2,3) #output layer

)


# print them out to have a look
print(widenetwork)
print(' ')
print(deepnetwork)



Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [14]:
#widenetwork
deepnetwork


Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)

 The ouput above depicts two different sequential models
 : the first model contains two layersw
 count all trainable parameters and include the bias
    layer 0 contains feature in with number 2 as input and output feature
 # hidden layer, the object (nn.Linear) is the weight metrics for input 2, 4 that connect to the hiddent layer - visual ,
  #its the transformation layer ( connecting arrows) that gets mapped to hidden layer

In [15]:
#check out the parameters - attribute in deepnetwork
for p in deepnetwork.named_parameters():
  print(p)
  print('')

('0.weight', Parameter containing:
tensor([[-0.4897,  0.1060],
        [ 0.4733, -0.4479]], requires_grad=True))

('0.bias', Parameter containing:
tensor([-0.2915,  0.4793], requires_grad=True))

('1.weight', Parameter containing:
tensor([[-0.6489, -0.3188],
        [-0.2988,  0.2866]], requires_grad=True))

('1.bias', Parameter containing:
tensor([ 0.0417, -0.6648], requires_grad=True))

('2.weight', Parameter containing:
tensor([[-0.0452,  0.2804],
        [ 0.1735, -0.0988],
        [ 0.4580,  0.5612]], requires_grad=True))

('2.bias', Parameter containing:
tensor([-0.5880,  0.2606, -0.2908], requires_grad=True))



output above is a set of variables or tuples
     elements are in side of tuples
     name is 0.weight
     the four values are actual weight values
     they are the weights that are associated with each arrow connecting to
     these numbers will change as the model is trained
     will the gradient affect the matrix during back propagation, so the requires_grad=True can be set to False.  Use defaul True for now.
     bias name is 0.bias - only two values, because the first layer has two nodes.
     


In [16]:
#count the number of nodes in each network( = the number of biases)
#Do for both networks
# every node in the network has one bias value, so count
# the number of times the string biases appears
#so loop through each networks and view each parameter
#and search for the string name 'bias' in each parameter
#if bias is found , then accumulate this total and display

#looking at the named_parameters() which is an iterable that returns the tuple (name,numbers)

numNodesInWide = 0
for p in widenetwork.named_parameters():
  if 'bias' in p[0]:   #first element in tuple
    numNodesInWide += len(p[1])  #second element in tuple with corresponds to the bias term


numNodesInDeep = 0
#using more interpreterable variables- helps to unpack network
for paramName, paramVect in deepnetwork.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)

print('There are %s nodes in the wide network. '  %numNodesInWide)
print('There are %s nodes in the deep network. ' %numNodesInDeep)

There are 7 nodes in the wide network. 
There are 7 nodes in the deep network. 


In [17]:
#Just the parameters only
#accessing the matrix of weights and bias
#parameters() does not provide the name like the named_parameters() method
for p in widenetwork.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[ 0.2453,  0.1243],
        [ 0.5080,  0.1516],
        [ 0.3101,  0.0464],
        [ 0.2599, -0.6829]], requires_grad=True)
 
Parameter containing:
tensor([ 0.3568, -0.2602, -0.4650,  0.4226], requires_grad=True)
 
Parameter containing:
tensor([[-0.4973,  0.4664,  0.4612, -0.2624],
        [ 0.1444,  0.0607,  0.2827,  0.2991],
        [-0.0252, -0.2714, -0.3501,  0.0600]], requires_grad=True)
 
Parameter containing:
tensor([ 0.2774, -0.0426,  0.1228], requires_grad=True)
 


In [18]:
#Now count the total number of trainable parameters

nparams = 0
for p in widenetwork.parameters():
  if p.requires_grad:  #if requires_grad is set to True
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameetrs' %nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameetrs


In [19]:
#can also use list comprehension

nparams = np.sum([p.numel() for p in widenetwork.parameters() if p.requires_grad])
print('Widenet has %s parameters' %nparams)

nparams = np.sum([p.numel() for p in deepnetwork.parameters() if p.requires_grad])
print('Deepnet has %s parameters' %nparams)



Widenet has 27 parameters
Deepnet has 21 parameters


In [20]:
#nice simple way to print out the model info.
#importing the function "summary" from the torchsummnary library
from torchsummary import summary
summary(widenetwork,(1,2)) #size of the input or the data matrix that I'm putting into the model

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
