<a href="https://colab.research.google.com/github/LLewis/ai-deep-learning/blob/main/LLewis_reproducible_random_seeding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reproducing random strings of numbers.
Making models reproducible

In [33]:
#import libraries
import numpy as np
import torch

#generare a few random numbers
np.random.randn(5)


#repeat after fixing the seeding (old - still widely used method)
#seed allows others that use the same algorithm to create the same values



array([-1.77528229,  1.31487654, -0.47344805, -1.0922299 , -0.25002744])

In [61]:
#repeat after fixing the seeding (old - still widely used method)
#seeding allow algorithm to generate the same values, if others use algorithm same values will be created
#will get exact same value
#Global seeding 
np.random.seed(17)  #17 is simple an arbitray nunmbers
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


In [40]:
#Here seeding is creating a local scope for the randomseed1 and randomseed2
#The RandomState method generates the seed state

randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20230501)

#invoking randn from each object randseed1 and randseed2
print(randseed1.randn(5)) # same sequence
print(randseed2.randn(5)) # different value from above, but same each time it's executed
print(randseed1.randn(5)) # same as two up
print(randseed2.randn(5)), print(' ') #same as two up


#no seeding - so different value every time executed
print(np.random.randn(5))


[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-1.35550887 -1.38033217  0.95720633  0.92706643 -0.21343521]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[-0.28782324 -0.61381924  0.07457001 -0.00252326  1.33012283]
 
[ 0.0991466   0.63792617  0.70311068 -0.91609315 -0.78601423]


In [63]:
#Using Pytorch randomness NO seeding
#Values will always be different
torch.randn(5)
print(torch.randn(5))


tensor([ 0.1534, -2.6631, -1.4311, -0.5483,  0.3232])


In [62]:
#Torch seeding - values will be the same at each run
torch.manual_seed(17)
print(torch.randn(5))

# torch's seeding does NOT spread to numpy
print(np.random.randn(5))



tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]
